#!/bin/sh

protected_branch='main'
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "$protected_branch" ]; then
    echo "\033[0;31m[ERROR] Direct push to '$protected_branch' is blocked!\033[0m"
    echo "Please create a pull request or merge from a feature branch."
    exit 1
fi
